[files]
# The following files will be excluded from spell check during commits
extend-exclude = [
    "third_party",
    "patches",
    "build",
    # Skip `intermidiate` check in these files
    "test/cpp/eager/task_tests/CMakeLists.txt",
    "test/cpp/eager/task_tests/hook_test_intermidiate.cc",
]

[default]
# Ignore 1-3 letter words, refer to https://github.com/crate-ci/typos/issues/1079
extend-ignore-words-re = ["^[a-zA-Z]{1,3}$"]

[default.extend-words]
# PaddlePaddle specific words
arange = "arange"
astroid = 'astroid'
cacl = 'cacl'
CANN = 'CANN'
Clas = 'Clas'
clen = 'clen'
datas = 'datas'
dota = 'dota'
dout = "dout"
eles = 'eles'
entrys = 'entrys'
feeded = 'feeded'
grad = "grad"
Halfs = 'Halfs'
kinf = 'kinf'
pash = 'pash'
unpacket = "unpacket"

# These words need to be fixed
Creater = 'Creater'
creater = 'creater'
dito = 'dito'
devide = 'devide'
documention = 'documention'
doens = 'doens'
doen = 'doen'
doubel = 'doubel'
dobule = 'dobule'
Dowloading = 'Dowloading'
downsteram = 'downsteram'
fetchs = 'fetchs'
Flattend = 'Flattend'
flattend = 'flattend'
flattern = 'flattern'
Flattern = 'Flattern'
filpped = 'filpped'
flaot = 'flaot'
follwed = 'follwed'
folowing = 'folowing'
formater = 'formater'
formating = 'formating'
foramt = 'foramt'
formate = 'formate'
formt = 'formt'
forwrad = 'forwrad'
forwad = 'forwad'
forword = 'forword'
founf = 'founf'
framwork = 'framwork'
frequence = 'frequence'
fron = 'fron'
fullfill = 'fullfill'
Indexs = 'Indexs'
indexs = 'indexs'
indiates = 'indiates'
indeces = 'indeces'
inferrence = 'inferrence'
Infered = 'Infered'
infered = 'infered'
infering = 'infering'
informations = 'informations'
imformation = 'imformation'
infomation = 'infomation'
Infor = 'Infor'
infor = 'infor'
inheritted = 'inheritted'
initilization = 'initilization'
initilized = 'initilized'
initalized = 'initalized'
initalize = 'initalize'
intialize = 'intialize'
inital = 'inital'
Inouts = 'Inouts'
intputs = 'intputs'
inputed = 'inputed'
intput = 'intput'
Intput = 'Intput'
inser = 'inser'
insid = 'insid'
insepection = 'insepection'
intall = 'intall'
instanciate = 'instanciate'
occured = 'occured'
Ocurred = 'Ocurred'
occures = 'occures'
offets = 'offets'
offseted = 'offseted'
Operants = 'Operants'
operants = 'operants'
oeprations = 'oeprations'
Opeartion = 'Opeartion'
operaion = 'operaion'
oppotunity = 'oppotunity'
optimzed = 'optimzed'
optmize = 'optmize'
optin = 'optin'
Optin = 'Optin'
rder = 'rder'
oreder = 'oreder'
orignal = 'orignal'
orginal = 'orginal'
onces = 'onces'
outter = 'outter'
outpus = 'outpus'
outout = 'outout'
ouput = 'ouput'
outpout = 'outpout'
ouptut = 'ouptut'
Ouput = 'Ouput'
overriden = 'overriden'
Overide = 'Overide'
overide = 'overide'
overrided = 'overrided'
Packge = 'Packge'
pacakage = 'pacakage'
padd = 'padd'
payed = 'payed'
parellel = 'parellel'
parm = 'parm'
Parm = 'Parm'
PARM = 'PARM'
paramters = 'paramters'
Paramters = 'Paramters'
paramter = 'paramter'
Paramater = 'Paramater'
paramete = 'paramete'
parmeter = 'parmeter'
paremeter = 'paremeter'
parrent = 'parrent'
parital = 'parital'
partitial = 'partitial'
Partitial = 'Partitial'
Partion = 'Partion'
partion = 'partion'
patition = 'patition'
passs = 'passs'
Passs = 'Passs'
pathes = 'pathes'
patten = 'patten'
Patten = 'Patten'
pattens = 'pattens'
precent = 'precent'
performace = 'performace'
perfomed = 'perfomed'
perfome = 'perfome'
presistable = 'presistable'
pyhsical = 'pyhsical'
pipline = 'pipline'
palce = 'palce'
Placment = 'Placment'
pleace = 'pleace'
Poniter = 'Poniter'
poped = 'poped'
positon = 'positon'
POSTION = 'POSTION'
postive = 'postive'
possiable = 'possiable'
potentialy = 'potentialy'
precending = 'precending'
Prepration = 'Prepration'
Prepar = 'Prepar'
preprocesser = 'preprocesser'
priorites = 'priorites'
probabalistic = 'probabalistic'
processer = 'processer'
proccess = 'proccess'
producted = 'producted'
progam = 'progam'
progrss = 'progrss'
propogated = 'propogated'
Propogation = 'Propogation'
protocal = 'protocal'
PROTOCAL = 'PROTOCAL'
pyrhon = 'pyrhon'
pthon = 'pthon'
qucik = 'qucik'
quitted = 'quitted'
runned = 'runned'
readed = 'readed'
recived = 'recived'
recevied = 'recevied'
reveived = 'reveived'
recieved = 'recieved'
recieves = 'recieves'
recive = 'recive'
receving = 'receving'
recommand = 'recommand'
recomplie = 'recomplie'
recored = 'recored'
Recusive = 'Recusive'
recusive = 'recusive'
recursivly = 'recursivly'
Recursivly = 'Recursivly'
reduntant = 'reduntant'
Refered = 'Refered'
refered = 'refered'
registed = 'registed'
regist = 'regist'
Regist = 'Regist'
Registe = 'Registe'
registe = 'registe'
REGIST = 'REGIST'
Regiter = 'Regiter'
releated = 'releated'
realease = 'realease'
relase = 'relase'
reomve = 'reomve'
Reoder = 'Reoder'
repeatly = 'repeatly'
repeate = 'repeate'
repalce = 'repalce'
represention = 'represention'
requied = 'requied'
Reqiured = 'Reqiured'
Requred = 'Requred'
requirments = 'requirments'
Reseting = 'Reseting'
reseted = 'reseted'
resouce = 'resouce'
retore = 'retore'
rewriten = 'rewriten'
rewrited = 'rewrited'
Runing = 'Runing'
runing = 'runing'
SMAE = 'SMAE'
satifies = 'satifies'
sclar = 'sclar'
sacle = 'sacle'
schduler = 'schduler'
sheduler = 'sheduler'
shedule = 'shedule'
scheule = 'scheule'
serach = 'serach'
seconde = 'seconde'
Seleceted = 'Seleceted'
sence = 'sence'
seperately = 'seperately'
seperate = 'seperate'
sepearate = 'sepearate'
seperating = 'seperating'
seperator = 'seperator'
sequnce = 'sequnce'
seqence = 'seqence'
sequece = 'sequece'
sequnece = 'sequnece'
sequentail = 'sequentail'
serailize = 'serailize'
settting = 'settting'
setted = 'setted'
shoule = 'shoule'
shoud = 'shoud'
Singal = 'Singal'
Similiar = 'Similiar'
simular = 'simular'
Simle = 'Simle'
signle = 'signle'
Skiped = 'Skiped'
skiped = 'skiped'
smll = 'smll'
samll = 'samll'
somme = 'somme'
patial = 'patial'
Patial = 'Patial'
specificed = 'specificed'
splite = 'splite'
spliter = 'spliter'
spliting = 'spliting'
Spliting = 'Spliting'
splited = 'splited'
splitted = 'splitted'
Splited = 'Splited'
sqaure = 'sqaure'
sequeze = 'sequeze'
starup = 'starup'
statment = 'statment'
staticly = 'staticly'
staticaly = 'staticaly'
Stati = 'Stati'
STOPED = 'STOPED'
Stoped = 'Stoped'
stoped = 'stoped'
storeage = 'storeage'
sotring = 'sotring'
stragety = 'stragety'
strem = 'strem'
structed = 'structed'
sturcture = 'sturcture'
subsituted = 'subsituted'
subsitute = 'subsitute'
substitude = 'substitude'
substitue = 'substitue'
Subsitute = 'Subsitute'
Substitude = 'Substitude'
substract = 'substract'
Substract = 'Substract'
successed = 'successed'
sucessfully = 'sucessfully'
Succeess = 'Succeess'
Suger = 'Suger'
supportted = 'supportted'
supoort = 'supoort'
Supprot = 'Supprot'
suport = 'suport'
suppport = 'suppport'
SWTICH = 'SWTICH'
Swith = 'Swith'
sysyem = 'sysyem'
targt = 'targt'
Taget = 'Taget'
templat = 'templat'
temporaily = 'temporaily'
temporily = 'temporily'
Temperarily = 'Temperarily'
temporaly = 'temporaly'
Temperary = 'Temperary'
tenosr = 'tenosr'
iterm = 'iterm'
termiante = 'termiante'
Theoritical = 'Theoritical'
ther = 'ther'
thge = 'thge'
thouse = 'thouse'
theads = 'theads'
thrads = 'thrads'
thre = 'thre'
THREAHOLD = 'THREAHOLD'
THORW = 'THORW'
timout = 'timout'
tiemout = 'tiemout'
TOOD = 'TOOD'
tood = 'tood'
TDOD = 'TDOD'
toghether = 'toghether'
trainning = 'trainning'
Traning = 'Traning'
transforme = 'transforme'
transfered = 'transfered'
transfering = 'transfering'
tranfers = 'tranfers'
tranfer = 'tranfer'
Tranfer = 'Tranfer'
transfrom = 'transfrom'
tranform = 'tranform'
Tranpose = 'Tranpose'
tranpose = 'tranpose'
tigger = 'tigger'
trimed = 'trimed'
trival = 'trival'
Trye = 'Trye'
Tring = 'Tring'
tring = 'tring'
tunning = 'tunning'
TYPLE = 'TYPLE'
trun = 'trun'
tyep = 'tyep'
tpye = 'tpye'
unchangable = 'unchangable'
Undefind = 'Undefind'
unser = 'unser'
UNEXPECT = 'UNEXPECT'
Unifrom = 'Unifrom'
uninitialzed = 'uninitialzed'
Uniqe = 'Uniqe'
unqiue = 'unqiue'
uniqe = 'uniqe'
unkown = 'unkown'
unkonwn = 'unkonwn'
Unkown = 'Unkown'
unsupport = 'unsupport'
upsupported = 'upsupported'
Unsupport = 'Unsupport'
UNSUPPORT = 'UNSUPPORT'
unziped = 'unziped'
udpated = 'udpated'
upgarde = 'upgarde'
uptream = 'uptream'
unsed = 'unsed'
uesd = 'uesd'
usefull = 'usefull'
usless = 'usless'
vaccum = 'vaccum'
valud = 'valud'
VAILD = 'VAILD'
valus = 'valus'
valuse = 'valuse'
Varible = 'Varible'
varaible = 'varaible'
vecotr = 'vecotr'
verson = 'verson'
vesion = 'vesion'
Vetical = 'Vetical'
vunerability = 'vunerability'
varn = 'varn'
warpped = 'warpped'
warpper = 'warpper'
Warpper = 'Warpper'
wheather = 'wheather'
wether = 'wether'
Wether = 'Wether'
wieghts = 'wieghts'
werid = 'werid'
Wheter = 'Wheter'
whther = 'whther'
whill = 'whill'
whos = 'whos'
wiil = 'wiil'
witk = 'witk'
worke = 'worke'
workround = 'workround'
worksapce = 'worksapce'
wrappered = 'wrappered'
wraper = 'wraper'
wraping = 'wraping'
Writter = 'Writter'
writed = 'writed'
